site_name: MtG Learn
site_url: https://www.mtg-learn.org/
theme:
  name: material

plugins:
  - search:
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_source: false
            show_root_heading: true
            show_full_root_path: false
            show_signature: true
            show_signature_annotations: true
nav:
  - Home: index.md
  - Docs: docs/index.md
  - Blog:
    - 2021:
      - blog/2022/hello-world.md