site_name: MtG Learn
site_url: https://www.mtg-learn.org/
theme:
  name: material

plugins:
  - search:
  - mkdocstrings:
      watch:
        - src

nav:
  - Home: index.md
  - Docs: docs/index.md
  - Blog:
    - 2021:
      - blog/2022/hello-world.md