name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build package
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          python setup.py bdist_wheel
      - name: Run tests
        run: |
          python -m pip install --upgrade pip
          python -m pip install mtglearn --find-links=dist/
          python -m pytest